# Generated by Django 6.0.2 on 2026-03-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_user_date_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
