# Generated by Django 4.2.27 on 2026-01-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_remove_message_metadata_remove_message_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='message',
            name='ai_response',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='message',
            name='is_user',
            field=models.BooleanField(default=True, help_text='是否為用戶訊息'),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default='', help_text='訊息內容'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
