# Generated by Django 6.0.2 on 2026-02-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, help_text='對話標題', max_length=50),
        ),
    ]
