# Generated by Django 6.0.2 on 2026-03-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_conversation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(help_text='訊息內容', max_length=500),
        ),
    ]
